# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-gwas
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - plink2
  - r=4.1.0
  - r-rmarkdown=2.11
  - r-ggplot2=3.3.5
  - r-dplyr=1.0.7
  - r-dt=0.19
  - r-qqman=0.1.8
  - r-htmltools=0.5.2
  - r-rmdformats=1.0.3
  - r-skimr=2.1.3
  - r-kableextra=1.3.4
  - r-data.table=1.14.0
  - r-r.utils=2.10.1
  - r-ggrepel=0.9.1
  - pandoc=2.14.2
  - cairo=1.16.0
  - xorg-libxt=1.2.1
  - fonts-anaconda=1
  - openjdk=11.0.9
  - unzip=6.0
  - bioconductor-ramwas=1.16.0
  - bedtools=2.30.0
  - htslib=1.14
