FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

LABEL author="Edoardo Giacopuzzi"
LABEL contact="edoardo.giacopuzzi@fht.org"
LABEL image_version="2.0"

# Install software
RUN apt-get update && \
    apt-get install -y \
    libcairo2-dev \
    libxt-dev \
    pandoc \
    wget \
    gfortran \
    build-essential \
    automake \
    python3 \
    python3-pip \
    bzip2 libbz2-dev zlib1g zlib1g-dev liblzma-dev libssl-dev libncurses5-dev \
    procps \
    ttf-mscorefonts-installer \
&& ln -s /usr/bin/python3 /usr/bin/python \
&& apt-get -y autoremove \
&& apt-get -y clean all \
&& rm -rf /var/cache 

# Install quarto
WORKDIR /opt
RUN wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.433/quarto-1.3.433-linux-amd64.tar.gz && \
    tar -zxvf quarto-1.3.433-linux-amd64.tar.gz && \
    rm quarto-1.3.433-linux-amd64.tar.gz
ENV PATH /opt/quarto-1.3.433/bin:$PATH

# Install htslib
WORKDIR /opt
RUN wget https://github.com/samtools/htslib/releases/download/1.15/htslib-1.15.tar.bz2 \
    && tar -jxvf htslib-1.15.tar.bz2; rm htslib-1.15.tar.bz2 \
    && cd htslib-1.15 \
    && ./configure \
    && make \
    && make install

# Install python packages
RUN pip install matplotlib==3.5.0 skimpy==0.0.9 papermill==2.4.0 && \
    pip install gwaslab==3.4.19 && \
    pip install pandas==1.4.4 

# Install reference data for gwaslab
RUN mkdir /gwaslab_data && chmod a+wr /gwaslab_data

WORKDIR /opt
COPY get_reference_data.py .
RUN python get_reference_data.py && \
    cd /gwaslab_data && \
    mkdir -p recombination/hg19 && \
    mkdir -p recombination/hg38 && \
    mv recombination_hg19.tar.gz recombination/hg19 && \
    mv recombination_hg38.tar.gz recombination/hg38 && \
    cd /gwaslab_data/recombination/hg19 && \
    tar -zxvf recombination_hg19.tar.gz && rm recombination_hg19.tar.gz && \
    cd /gwaslab_data/recombination/hg38 && \
    tar -zxvf recombination_hg38.tar.gz && rm recombination_hg38.tar.gz